"""Detection signals for Provenance Guard.

Each signal takes raw text and returns a float in [0, 1] where
1 = strongly AI-generated, 0 = strongly human-written.

M3: llm_signal only. Signal 2 (stylometric) is added in M4.
"""
import os
import json
from groq import Groq

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def llm_signal(text):
    """Signal 1 — semantic/holistic. Returns 0-1 (1 = strongly AI)."""
    prompt = (
        "You are an AI-content detector. Estimate how likely the following text "
        "was generated by an AI language model. Return an integer 0-100 where "
        "100 = almost certainly AI and 0 = almost certainly human-written. "
        'Respond ONLY with JSON, no prose, no code fences: '
        '{"score": <int 0-100>, "reason": "<one short sentence>"}\n\n'
        f"TEXT:\n{text}"
    )
    resp = _get_client().chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )
    raw = resp.choices[0].message.content.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()
    data = json.loads(raw)
    score = max(0, min(100, int(data["score"])))
    return score / 100.0
